version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  pull-request-branch-name:
    separator: "-"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 3
  allow:
      - dependency-type: "direct"
  reviewers:
      - "mleralec"
