defaults: &defaults
  working_directory: ~/front-config

restore_repo: &restore_repo
  restore_cache:
    keys:
      - v-20-source-{{ .Branch }}-{{ .Revision }}

version: 2.1

orbs:
  aws-s3: circleci/aws-s3@2.0.0

jobs:
  checkout:
    <<: *defaults
    docker:
      - image: cimg/node:16.13.2
    steps:
      - *restore_repo
      - checkout
      - restore_cache:
          key: v-20-yarn-{{ checksum "yarn.lock" }}
      - run:
          name: install dependencies
          command: yarn
      - save_cache:
          key: v-20-yarn-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - save_cache:
          key: v-20-source-{{ .Branch }}-{{ .Revision }}
          paths:
            - ~/front-config

  vulnerabilities_yarn:
    <<: *defaults
    docker:
      - image: cimg/node:16.16.0
    steps:
      - *restore_repo
      - run:
          name: Critical vulnerabilities test (yarn audit)
          command: yarn check:audit

  lint:
    <<: *defaults
    docker:
      - image: cimg/node:16.13.2
        environment:
          NODE_ENV: test
    steps:
      - *restore_repo
      - run:
          name: linter
          command: yarn lint

workflows:
  version: 2
  test_and_build:
    jobs:
      - checkout
      - vulnerabilities_yarn:
          requires:
            - checkout
      - lint:
          requires:
            - vulnerabilities_yarn
